### ISSUE TITLE
error office-app-for-outlook-angular@0.1.0 install: `bower install`

### ISSUE THREAD

**Issue by hitendramalviya** [matejv1/outlook-addin-office365-api#1]
While running npm install it is not able to recognise bower command and saying 'bower' is not recognized as an internal or external command.
![capture](https://cloud.githubusercontent.com/assets/5709606/9693012/afbf2f9e-536a-11e5-8da8-571244ee7c36.PNG)

**Comment by matejv1** [comment]
Install bower as well.
